function [hdl] = load_headers(hdl)

hdl.TIME_header={'FRAME' 'TIME'};
hdl.FILE_header={'PATHNAME' 'FILENAME' 'COND1' 'COND2' 'COND3' 'ANIMAL' 'GAIT_TYPE' 'LIMB' 'SIDE'};

hdl.DATA_KIN_HL_header=[hdl.TIME_header, ...
    {'Scap left X' 'Scap left Y' 'Scap left Z' 'Crest left X' 'Crest left Y' 'Crest left Z' 'Hip left X' 'Hip left Y' 'Hip left Z' 'Knee left X' 'Knee left Y' 'Knee left Z' 'Ankle left X' 'Ankle left Y' 'Ankle left Z' 'MetaTarso left X' 'MetaTarso left Y' 'MetaTarso left Z' 'TIP left X' 'TIP left Y' 'TIP left Z' ...
    'Scap right X' 'Scap right Y' 'Scap right Z' 'Crest right X' 'Crest right Y' 'Crest right Z' 'Hip right X' 'Hip right Y' 'Hip right Z' 'Knee right X' 'Knee right Y' 'Knee right Z' 'Ankle right X' 'Ankle right Y' 'Ankle right Z' 'MetaTarso right X' 'MetaTarso right Y' 'MetaTarso right Z' 'TIP right X' 'TIP right Y' 'TIP right Z'}];

hdl.DATA_KIN_FL_header=[hdl.TIME_header, ...
    {'Shoulder left X' 'Shoulder left Y' 'Shoulder left Z' 'Crest left X' 'Crest left Y' 'Crest left Z' 'Hip left X' 'Hip left Y' 'Hip left Z' 'Knee left X' 'Knee left Y' 'Knee left Z' 'Ankle left X' 'Ankle left Y' 'Ankle left Z' 'MetaTarso left X' 'MetaTarso left Y' 'MetaTarso left Z' 'TIP left X' 'TIP left Y' 'TIP left Z' ...
    'Shoulder right X' 'Shoulder right Y' 'Shoulder right Z' 'Crest right X' 'Crest right Y' 'Crest right Z' 'Hip right X' 'Hip right Y' 'Hip right Z' 'Knee right X' 'Knee right Y' 'Knee right Z' 'Ankle right X' 'Ankle right Y' 'Ankle right Z' 'MetaTarso right X' 'MetaTarso right Y' 'MetaTarso right Z' 'TIP right X' 'TIP right Y' 'TIP right Z'...
    'Elbow left X' 'Elbow left Y' 'Elbow left Z' 'Wrist left X' 'Wrist left Y' 'Wrist left Z'...
    'Elbow right X' 'Elbow right Y' 'Elbow right Z' 'Wrist right X' 'Wrist right Y' 'Wrist right Z'...
    'Scap left X' 'Scap left Y' 'Scap left Z' ...
    'Scap right X' 'Scap right Y' 'Scap right Z' ...
    'T12 X' 'T12 Y' 'T12 Z' 'HeadFront X' 'HeadFront Y' 'HeadFront Z' ...
    'Ear left X' 'Ear left Y' 'Ear left Z' ...
    'Ear right X' 'Ear right Y' 'Ear right Z' ...
    'Toe left X' 'Toe left Y' 'Toe left Z' 'Toe right X' 'Toe right Y' 'Toe right Z'}]; 
    % if TRUNK marker is present {'Trunk X' 'Trunk Y' 'Trunk Z'} is added at the end of .DATA_KIN_FL_header in ggait

hdl.ANGLES_LHL_header={'ELEV CrestL' 'ELEV ThighL' 'ELEV LegL' 'ELEV FootL' 'ELEV ToeL' 'HindlimbL' 'JOINT HipL' 'JOINT KneeL' 'JOINT AnkleL' 'JOINT MTPL' 'HindlimbL_LAT' 'FootL_ROT'};
hdl.ANGLES_RHL_header={'ELEV CrestR' 'ELEV ThighR' 'ELEV LegR' 'ELEV FootR' 'ELEV ToeR' 'HindlimbR' 'JOINT HipR' 'JOINT KneeR' 'JOINT AnkleR' 'JOINT MTPR' 'HindlimbR_LAT' 'FootR_ROT'};
hdl.ANGLES_trunk_header={'MidSh_X' 'MidSh_Y' 'MidSh_Z' 'MidHip_X' 'MidHip_Y' 'MidHip_Z' 'ELEV MidTrunk1' 'ELEV TrunkR' 'ELEV TrunkL' 'ELEV MidTrunk2' 'Shoulders' 'Hips' 'MidCrest_X' 'MidCrest_Y' 'MidCrest_Z'};
    % if TRUNK marker is present {'JOINT Trunk'} is added at the end of .ANGLES_trunk_header in ggait
hdl.ANGLES_HL_header=[hdl.ANGLES_LHL_header,hdl.ANGLES_RHL_header hdl.ANGLES_trunk_header];

hdl.ANGLES_LFL_header={'ELEV ScapulaL' 'ELEV ArmL' 'ELEV ForearmL' 'ELEV HandL' 'ELEV FingerL' 'ForelimbL' 'JOINT ScapL' 'JOINT ShoulderL' 'JOINT ElbowL' 'JOINT WristL' 'ForelimbL_LAT' 'EMPTY'};
hdl.ANGLES_RFL_header={'ELEV ScapulaR' 'ELEV ArmR' 'ELEV ForearmR' 'ELEV HandR' 'ELEV FingerR' 'ForelimbR' 'JOINT ScapR' 'JOINT ShoulderR' 'JOINT ElbowR' 'JOINT WristR' 'ForelimbR_LAT' 'EMPTY'};
hdl.ANGLES_FL_header=[hdl.ANGLES_LFL_header hdl.ANGLES_RFL_header];

hdl.DATA_EMG_header={};

hdl.DATA_FORCE_heading={'Force X' 'Force Y' 'Force Z' 'Moment X' 'Moment Y' 'Moment Z'};
hdl.DATA_FORCE_header=[hdl.TIME_header, hdl.DATA_FORCE_heading];
 
hdl.DATA_CoP_header=[hdl.TIME_header, {'CoP X' 'CoP Y'}];

hdl.DATA_NEU_header={};

hdl.GAIT_INFO_header={'EMPTY' 'Left strike' 'Left MIN limb' 'Left off' 'EMPTY' ...
                  'EMPTY' 'Right strike' 'Right MIN limb' 'Right off'};
              
hdl.ENDPOINT_PCA_header= {'ANIMAL' 'COND1' 'COND2' 'SIDE' 'SPEED' 'PCAx' 'PCAy' 'PCAz' 'PCAxy' 'PCAxyz'};

hdl.GAIT_header= {'ANIMAL' 'CONDITION 1' 'CONDITION 2' 'LIMB SIDE' 'SPEED' 'CYCLE' 'G ONSET' 'G END' 'T ONSET' 'T END' 'DURATION' ...
    'L STRIDE' 'VELOCITY' 'STANCE' 'ST DUR' 'SW DUR' '%ST DUR' 'L STEP' 'STEP WIDTH'...
    'SD MidSh Y' 'SD MidSh Z' 'SD MidHip Y' 'SD MidHip Z' 'SD MidTrunk XY' 'SD MidTrunk XY Vel' 'SD Shoulders' 'SD Hips'...
    'STEP HEIGHT' 'STEP HEIGHT nor' 'HIP-END BW' 'HIP-END FW'...
    'ST contra HL' 'SW contra HL' 'L PATH' 'MAX ENDPOINT Vel' 'T MAX ENDPOINT Vel' 'BWS'...
    'MAX ELE 1' 'MIN ELE 1' 'MAX ELE 2' 'MIN ELE 2' 'MAX ELE 3' 'MIN ELE 3' 'MAX ELE 4' 'MIN ELE 4' 'MAX ELE 5' 'MIN ELE 5' 'MAX ELE 6' 'MIN ELE 6'...
    'MAX JOINT 1' 'MIN JOINT 1' 'MAX JOINT 2' 'MIN JOINT 2' 'MAX JOINT 3' 'MIN JOINT 3' 'MAX JOINT 4' 'MIN JOINT 4'...
    'MAX LIMBLAT' 'MIN LIMBLAT' 'MAX FOOTROT' 'MIN  FOOTROT'...
    'T DRAG END' 'T DRAG' '%DRAG'...
    'PC1' 'PC2' 'PC3' 'PC4' 'PCA5'...
    'PC1' 'PC2' 'PC3' 'PC4' 'LAG HINDLIMBS' 'Rt=0 HINDLIMBS' 'LAG HL IPSIFL' 'Rt=0 HL IPSIFL' 'LAG HL CONFL' 'Rt=0 HL CONFL' ...
    'PH1' 'AMP1' 'PH2' 'AMP2' 'PH3' 'AMP3' 'PH4' 'AMP4' 'PH5' 'AMP5' 'PH2 PH1' 'PH3 PH2' 'PH4 PH3' 'PH5 PH4'...
    'LAG CREST-THIGH' 'R CREST-THIGH' 'LAG THIGH-LEG' 'R THIGH-LEG' 'LAG LEG-FOOT' 'R LEG-FOOT' 'LAG FOOT - TOE' 'R FOOT - TOE' ...
    'LAG HIP-KNEE' 'R HIP-KNEE' 'LAG KNEE-ANKLE' 'R KNEE-ANKLE' 'LAG ANKLE-MTP' 'R ANKLE-MTP' ...
    'DOUBLE STANCE' 'Acc ENDPOINT' 'FOOT SW LAT' 'Kin AVE' 'Vel ENDPOINT' 'Angle Vel ENPOINT'...
    'AMP ELE 1' 'AMP ELE 2' 'AMP ELE 3' 'AMP ELE 4' 'AMP ELE 5' 'AMP LIMB'...
    'AMP JOINT 1' 'AMP JOINT 2' 'AMP JOINT 3' 'AMP JOINT 4' ...
    'AMP LIMBLAT' 'AMP FOOTROT' 'MAX HipY nor' 'MIN HipY nor' 'AMP HipY' ...
    'Xfor STANCE' 'Yfor STANCE' 'Zfor STANCE' 'Xfor singleSTANCE' 'Yfor singleSTANCE' 'Zfor singleSTANCE'...
    'LIMB_lag', 'LIMB_R', 'HIP lag', 'HIP R','KNEE lag', 'KNEE R','ANKLE lag', 'ANKLE R','MTP lag', 'MTP R'...
    'CREST-THIGH timingMIN', 'CREST-THIGH timingMAX', 'THIGH-LEG timingMIN', 'THIGH-LEG timingMAX','LEG-FOOT timingMIN', 'LEG-FOOT timingMAX','FOOT-TOE timingMIN', 'FOOT-TOE timingMAX' ...
    'MAX SPEEDLIMB 1' 'MIN SPEEDLIMB 1' 'AMP SPEEDLIMB 1' 'MAX SPEEDJOINT 1' 'MIN SPEEDJOINT 1' 'AMP SPEEDJOINT 1' 'MAX SPEEDJOINT 2' 'MIN SPEEDJOINT 2' 'AMP SPEEDJOINT 2' ...
    'MAX SPEEDJOINT 3' 'MIN SPEEDJOINT 3' 'AMP SPEEDJOINT 3' 'MAX SPEEDJOINT 4' 'MIN SPEEDJOINT 4' 'AMP SPEEDJOINT 4'...
    'Stance IPSIFORE' 'Swing IPSIFORE' 'Stance CONTRAFORE' 'Swing CONTRAFORE' 'FLIGHT' 'STANCE ONE LIMB' 'STANCE TWO LIMBS' 'STANCE THREE LIMBS' 'STANCE FOUR LIMBS' ...
    'L VirtCOM fw' 'L VirtCOM lat' 'L VirtCOM vert' 'L VirtCOM 3D'...
    'FootLADDER_h' 'FootLADDER_v' 'Perc_FootLADDER' 'MAX JOINT TRUNK' 'MIN JOINT TRUNK' 'AMP JOINT TRUNK' 'MAX SPEEDJOINT TRUNK' 'MIN SPEEDJOINT TRUNK' 'AMP SPEEDJOINT TRUNK'}; ...];

hdl.DATA_GAIT_header_REF=[-10	-9	-8	-7	-6	-5	-4	-3	-2	-1	1	20 ...
    2	500	3	4	5	21	41	49	50	48	47	45	46	60	61	501	25	23	24 ...
    13	14	22	26	27	173	76	70	77	71	78	72	79	73	80	74	81	75	82	88 ...
    83	89	84	90	85	91	86	92	87	93	502	31	32	130	503	504	505	506	507	...
    508	509	510	511	6	512	15	513	16	514	515	516	517	518	519	520	521	522	523	131	132 ...
    133	134	524	135	525	136	526	137	527	138	528	139	529	140	530	141	7	28	40	531	29 ...
    30	94	95	96	97	98	99	100	101	102	103	104	105	42	43	44	172	170	171	532	...
    533	534	180	181	182	183	184	185	186	187	188	189	142	143	144	145	146	147	148	149	115	...
    110	120	116	111	121	117	112	122	118	113	123	119	114	124	535	536	537	538	8	9	10	11 ...
    12 62 63 64 65 36 37 38 539 540 541 542 543 544];

hdl.DATA_SumAverage_header={'Animal' 'Condition1' 'Condition2' 'LimbSide' 'Speed'...
    'MinFootspeed' 'MaxFootspeed' 'AMPFootspeed' 'MeanFootspeed'...
    'MinLimbspeed' 'MaxLimbspeed' 'AMPLimbspeed' 'MeanLimbspeed'...
    'MinHipspeed' 'MaxHipspeed' 'AMPHipspeed' 'MeanHipspeed'...
    'MinKneespeed' 'MaxKneespeed' 'AMPKneespeed' 'MeanKneespeed'...
    'MinAnklespeed' 'MaxAnklespeed' 'AMPAnklespeed' 'MeanAnklespeed'...
    'MinMTPspeed' 'MaxMTPspeed' 'AMPMTPspeed' 'MeanMTPspeed'...
    'MinAB/AD PELVISspeed' 'MaxAB/AD PELVISspeed' 'AMPAB/AD PELVISspeed' 'MeanAB/AD PELVISspeed'...
    'MinROT PELVISspeed' 'MaxROT PELVISspeed' 'AMPROT PELVISspeed' 'MeanROT PELVISspeed'...
    'SD crest' 'SD thigh', 'SD leg' 'SD foot' 'SD toe' 'SD limb' 'SD hip' 'SD knee' 'SD ankle' 'SD MTP' 'SD AB/AD pelvis' 'SD ROT pelvis'...
    'lag LIMB' 'R LIMB' 'lag HIP' 'R HIP' 'lag KNEE' 'R KNEE' 'lag ANKLE' 'R ANKLE' 'lag MTP' 'R MTP' ...
    'lag LIMBspeed' 'R LIMBspeed' 'lag HIPspeed' 'R HIPspeed' 'lag KNEEspeed' 'R KNEEspeed' 'lag ANKLEspeed' 'R ANKLEspeed' 'lag MTPspeed' 'R MTPspeed'...
    'LAG HIP-HIP' 'R HIP-HIP' 'LAG HIP-KNEE' 'R HIP-KNEE' 'LAG HIP-ANKLE' 'R HIP-ANKLE' 'LAG HIP-MTP' 'R HIP-MTP'...
    'LAG KNEE-HIP' 'R KNEE-HIP' 'LAG KNEE-KNEE' 'R KNEE-KNEE' 'LAG KNEE-ANKLE' 'R KNEE-ANKLE' 'LAG KNEE-MTP' 'R KNEE-MTP'...
    'LAG ANKLE-HIP' 'R ANKLE-HIP' 'LAG ANKLE-KNEE' 'R ANKLE-KNEE' 'LAG ANKLE-ANKLE' 'R ANKLE-ANKLE' 'LAG ANKLE-MTP' 'R ANKLE-MTP'...
    'LAG MTP-HIP' 'R MTP-HIP' 'LAG MTP-KNEE' 'R MTP-KNEE' 'LAG MTP-ANKLE' 'R MTP-ANKLE' 'LAG MTP-MTP' 'R MTP-MTP'...
    'DURATION' 'lag LIMB Left-Right' 'R LIMB Left-Right' 'DURATION' 'Rmin at t=0' 'FFT INTERLIMB'...
    'SD crest 0-10' 'SD crest 10-20' 'SD crest 20-30' 'SD crest 30-40' 'SD crest 40-50' 'SD crest 50-60' 'SD crest 60-70' 'SD crest 70-80' 'SD crest 80-90' 'SD crest 90-100' 'SD crest MID-STANCE' 'SD crest MID-SWING'...
    'SD thigh 0-10' 'SD thigh 10-20' 'SD thigh 20-30' 'SD thigh 30-40' 'SD thigh 40-50' 'SD thigh 50-60' 'SD thigh 60-70' 'SD thigh 70-80' 'SD thigh 80-90' 'SD thigh 90-100' 'SD thigh MID-STANCE' 'SD thigh MID-SWING'...
    'SD leg 0-10' 'SD leg 10-20' 'SD leg 20-30' 'SD leg 30-40' 'SD leg 40-50' 'SD leg 50-60' 'SD leg 60-70' 'SD leg 70-80' 'SD leg 80-90' 'SD leg 90-100' 'SD leg MID-STANCE' 'SD leg MID-SWING'...
    'SD foot 0-10' 'SD foot 10-20' 'SD foot 20-30' 'SD foot 30-40' 'SD foot 40-50' 'SD foot 50-60' 'SD foot 60-70' 'SD foot 70-80' 'SD foot 80-90' 'SD foot 90-100' 'SD foot MID-STANCE' 'SD foot MID-SWING'...
    'SD toe 0-10' 'SD toe 10-20' 'SD toe 20-30' 'SD toe 30-40' 'SD toe 40-50' 'SD toe 50-60' 'SD toe 60-70' 'SD toe 70-80' 'SD toe 80-90' 'SD toe 90-100' 'SD toe MID-STANCE' 'SD toe MID-SWING'...
    'SD limb 0-10' 'SD limb 10-20' 'SD limb 20-30' 'SD limb 30-40' 'SD limb 40-50' 'SD limb 50-60' 'SD limb 60-70' 'SD limb 70-80' 'SD limb 80-90' 'SD limb 90-100' 'SD limb MID-STANCE' 'SD limb MID-SWING'...
    'SD hip 0-10' 'SD hip 10-20' 'SD hip 20-30' 'SD hip 30-40' 'SD hip 40-50' 'SD hip 50-60' 'SD hip 60-70' 'SD hip 70-80' 'SD hip 80-90' 'SD hip 90-100' 'SD hip MID-STANCE' 'SD hip MID-SWING'...
    'SD knee 0-10' 'SD knee 10-20' 'SD knee 20-30' 'SD knee 30-40' 'SD knee 40-50' 'SD knee 50-60' 'SD knee 60-70' 'SD knee 70-80' 'SD knee 80-90' 'SD knee 90-100' 'SD knee MID-STANCE' 'SD knee MID-SWING'...
    'SD ankle 0-10' 'SD ankle 10-20' 'SD ankle 20-30' 'SD ankle 30-40' 'SD ankle 40-50' 'SD ankle 50-60' 'SD ankle 60-70' 'SD ankle 70-80' 'SD ankle 80-90' 'SD ankle 90-100' 'SD ankle MID-STANCE' 'SD ankle MID-SWING'...
    'SD MTP 0-10' 'SD MTP 10-20' 'SD MTP 20-30' 'SD MTP 30-40' 'SD MTP 40-50' 'SD MTP 50-60' 'SD MTP 60-70' 'SD MTP 70-80' 'SD MTP 80-90' 'SD MTP 90-100' 'SD MTP MID-STANCE' 'SD MTP MID-SWING'...
    'SD ABpelvis 0-10' 'SD ABpelvis 10-20' 'SD ABpelvis 20-30' 'SD ABpelvis 30-40' 'SD ABpelvis 40-50' 'SD ABpelvis 50-60' 'SD ABpelvis 60-70' 'SD ABpelvis 70-80' 'SD ABpelvis 80-90' 'SD ABpelvis 90-100' 'SD ABpelvis MID-STANCE' 'SD ABpelvis MID-SWING'...
    'SD ROTpelvis 0-10' 'SD ROTpelvis 10-20' 'SD ROTpelvis 20-30' 'SD ROTpelvis 30-40' 'SD ROTpelvis 40-50' 'SD ROTpelvis 50-60' 'SD ROTpelvis 60-70' 'SD ROTpelvis 70-80' 'SD ROTpelvis 80-90' 'SD ROTpelvis 90-100' 'SD ROTpelvis MID-STANCE' 'SD ROTpelvis MID-SWING'};


hdl.DATA_SD_REF=[11;12;15;16;19;24;25;29;30;31;32;34;35;36;63;90;91;92;93;108;109;112;113];
for i=1:size(hdl.DATA_SD_REF,1)
    hdl.DATA_SD_header(i)={['SD ', char(hdl.GAIT_header(hdl.DATA_SD_REF(i)))]};
end

% NOT USED YET
hdl.NonDisabled_header = {'ELEV Crest', 'ELEV Thigh', 'ELEV Leg', 'ELEV Foot', 'ELEV Toe', 'Hindlimb', ...
    'JOINT Hip', 'JOINT Knee', 'JOINT Ankle', 'JOINT MTP', 'Hindlimb_LAT', 'Foot_ROT'};


